// Generated by gencpp from file turtle_controll/pos_arr.msg
// DO NOT EDIT!


#ifndef TURTLE_CONTROLL_MESSAGE_POS_ARR_H
#define TURTLE_CONTROLL_MESSAGE_POS_ARR_H

#include <ros/service_traits.h>


#include <turtle_controll/pos_arrRequest.h>
#include <turtle_controll/pos_arrResponse.h>


namespace turtle_controll
{

struct pos_arr
{

typedef pos_arrRequest Request;
typedef pos_arrResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pos_arr
} // namespace turtle_controll


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtle_controll::pos_arr > {
  static const char* value()
  {
    return "6f5034cd178112665aad97185833de12";
  }

  static const char* value(const ::turtle_controll::pos_arr&) { return value(); }
};

template<>
struct DataType< ::turtle_controll::pos_arr > {
  static const char* value()
  {
    return "turtle_controll/pos_arr";
  }

  static const char* value(const ::turtle_controll::pos_arr&) { return value(); }
};


// service_traits::MD5Sum< ::turtle_controll::pos_arrRequest> should match 
// service_traits::MD5Sum< ::turtle_controll::pos_arr > 
template<>
struct MD5Sum< ::turtle_controll::pos_arrRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_controll::pos_arr >::value();
  }
  static const char* value(const ::turtle_controll::pos_arrRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_controll::pos_arrRequest> should match 
// service_traits::DataType< ::turtle_controll::pos_arr > 
template<>
struct DataType< ::turtle_controll::pos_arrRequest>
{
  static const char* value()
  {
    return DataType< ::turtle_controll::pos_arr >::value();
  }
  static const char* value(const ::turtle_controll::pos_arrRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtle_controll::pos_arrResponse> should match 
// service_traits::MD5Sum< ::turtle_controll::pos_arr > 
template<>
struct MD5Sum< ::turtle_controll::pos_arrResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_controll::pos_arr >::value();
  }
  static const char* value(const ::turtle_controll::pos_arrResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_controll::pos_arrResponse> should match 
// service_traits::DataType< ::turtle_controll::pos_arr > 
template<>
struct DataType< ::turtle_controll::pos_arrResponse>
{
  static const char* value()
  {
    return DataType< ::turtle_controll::pos_arr >::value();
  }
  static const char* value(const ::turtle_controll::pos_arrResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLE_CONTROLL_MESSAGE_POS_ARR_H
