// Generated by gencpp from file turtle_controll/pos_arrRequest.msg
// DO NOT EDIT!


#ifndef TURTLE_CONTROLL_MESSAGE_POS_ARRREQUEST_H
#define TURTLE_CONTROLL_MESSAGE_POS_ARRREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtle_controll
{
template <class ContainerAllocator>
struct pos_arrRequest_
{
  typedef pos_arrRequest_<ContainerAllocator> Type;

  pos_arrRequest_()
    : x()
    , y()  {
      x.assign(0);

      y.assign(0);
  }
  pos_arrRequest_(const ContainerAllocator& _alloc)
    : x()
    , y()  {
  (void)_alloc;
      x.assign(0);

      y.assign(0);
  }



   typedef boost::array<int32_t, 5>  _x_type;
  _x_type x;

   typedef boost::array<int32_t, 5>  _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::turtle_controll::pos_arrRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_controll::pos_arrRequest_<ContainerAllocator> const> ConstPtr;

}; // struct pos_arrRequest_

typedef ::turtle_controll::pos_arrRequest_<std::allocator<void> > pos_arrRequest;

typedef boost::shared_ptr< ::turtle_controll::pos_arrRequest > pos_arrRequestPtr;
typedef boost::shared_ptr< ::turtle_controll::pos_arrRequest const> pos_arrRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_controll::pos_arrRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_controll::pos_arrRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtle_controll

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtle_controll::pos_arrRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_controll::pos_arrRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_controll::pos_arrRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_controll::pos_arrRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_controll::pos_arrRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_controll::pos_arrRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_controll::pos_arrRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e059831c211d65c59f5fe447223afb4";
  }

  static const char* value(const ::turtle_controll::pos_arrRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e059831c211d65cULL;
  static const uint64_t static_value2 = 0x59f5fe447223afb4ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_controll::pos_arrRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_controll/pos_arrRequest";
  }

  static const char* value(const ::turtle_controll::pos_arrRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_controll::pos_arrRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[5] x\n\
int32[5] y\n\
";
  }

  static const char* value(const ::turtle_controll::pos_arrRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_controll::pos_arrRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pos_arrRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_controll::pos_arrRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_controll::pos_arrRequest_<ContainerAllocator>& v)
  {
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.y[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_CONTROLL_MESSAGE_POS_ARRREQUEST_H
