// Generated by gencpp from file service_demo/two_ints.msg
// DO NOT EDIT!


#ifndef SERVICE_DEMO_MESSAGE_TWO_INTS_H
#define SERVICE_DEMO_MESSAGE_TWO_INTS_H

#include <ros/service_traits.h>


#include <service_demo/two_intsRequest.h>
#include <service_demo/two_intsResponse.h>


namespace service_demo
{

struct two_ints
{

typedef two_intsRequest Request;
typedef two_intsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct two_ints
} // namespace service_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service_demo::two_ints > {
  static const char* value()
  {
    return "f4ab17e216a90fce307b72981813b6f5";
  }

  static const char* value(const ::service_demo::two_ints&) { return value(); }
};

template<>
struct DataType< ::service_demo::two_ints > {
  static const char* value()
  {
    return "service_demo/two_ints";
  }

  static const char* value(const ::service_demo::two_ints&) { return value(); }
};


// service_traits::MD5Sum< ::service_demo::two_intsRequest> should match 
// service_traits::MD5Sum< ::service_demo::two_ints > 
template<>
struct MD5Sum< ::service_demo::two_intsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service_demo::two_ints >::value();
  }
  static const char* value(const ::service_demo::two_intsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_demo::two_intsRequest> should match 
// service_traits::DataType< ::service_demo::two_ints > 
template<>
struct DataType< ::service_demo::two_intsRequest>
{
  static const char* value()
  {
    return DataType< ::service_demo::two_ints >::value();
  }
  static const char* value(const ::service_demo::two_intsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service_demo::two_intsResponse> should match 
// service_traits::MD5Sum< ::service_demo::two_ints > 
template<>
struct MD5Sum< ::service_demo::two_intsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service_demo::two_ints >::value();
  }
  static const char* value(const ::service_demo::two_intsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_demo::two_intsResponse> should match 
// service_traits::DataType< ::service_demo::two_ints > 
template<>
struct DataType< ::service_demo::two_intsResponse>
{
  static const char* value()
  {
    return DataType< ::service_demo::two_ints >::value();
  }
  static const char* value(const ::service_demo::two_intsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_DEMO_MESSAGE_TWO_INTS_H
