// Generated by gencpp from file service_demo/two_intsResponse.msg
// DO NOT EDIT!


#ifndef SERVICE_DEMO_MESSAGE_TWO_INTSRESPONSE_H
#define SERVICE_DEMO_MESSAGE_TWO_INTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace service_demo
{
template <class ContainerAllocator>
struct two_intsResponse_
{
  typedef two_intsResponse_<ContainerAllocator> Type;

  two_intsResponse_()
    : sum_2ints(0)
    , mul_2ints(0)
    , sub_2ints(0)
    , div_2ints(0.0)  {
    }
  two_intsResponse_(const ContainerAllocator& _alloc)
    : sum_2ints(0)
    , mul_2ints(0)
    , sub_2ints(0)
    , div_2ints(0.0)  {
  (void)_alloc;
    }



   typedef int64_t _sum_2ints_type;
  _sum_2ints_type sum_2ints;

   typedef int64_t _mul_2ints_type;
  _mul_2ints_type mul_2ints;

   typedef int64_t _sub_2ints_type;
  _sub_2ints_type sub_2ints;

   typedef double _div_2ints_type;
  _div_2ints_type div_2ints;





  typedef boost::shared_ptr< ::service_demo::two_intsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::service_demo::two_intsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct two_intsResponse_

typedef ::service_demo::two_intsResponse_<std::allocator<void> > two_intsResponse;

typedef boost::shared_ptr< ::service_demo::two_intsResponse > two_intsResponsePtr;
typedef boost::shared_ptr< ::service_demo::two_intsResponse const> two_intsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::service_demo::two_intsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::service_demo::two_intsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace service_demo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::service_demo::two_intsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_demo::two_intsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::service_demo::two_intsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::service_demo::two_intsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_demo::two_intsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_demo::two_intsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::service_demo::two_intsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "61c4a99f6ac6682b96e4622b970c9c45";
  }

  static const char* value(const ::service_demo::two_intsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x61c4a99f6ac6682bULL;
  static const uint64_t static_value2 = 0x96e4622b970c9c45ULL;
};

template<class ContainerAllocator>
struct DataType< ::service_demo::two_intsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "service_demo/two_intsResponse";
  }

  static const char* value(const ::service_demo::two_intsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::service_demo::two_intsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 sum_2ints\n\
int64 mul_2ints\n\
int64 sub_2ints\n\
float64 div_2ints\n\
\n\
";
  }

  static const char* value(const ::service_demo::two_intsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::service_demo::two_intsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum_2ints);
      stream.next(m.mul_2ints);
      stream.next(m.sub_2ints);
      stream.next(m.div_2ints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct two_intsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::service_demo::two_intsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::service_demo::two_intsResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum_2ints: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum_2ints);
    s << indent << "mul_2ints: ";
    Printer<int64_t>::stream(s, indent + "  ", v.mul_2ints);
    s << indent << "sub_2ints: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sub_2ints);
    s << indent << "div_2ints: ";
    Printer<double>::stream(s, indent + "  ", v.div_2ints);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVICE_DEMO_MESSAGE_TWO_INTSRESPONSE_H
